server:
  port:8081

spring:
  datesource:
    driver:com.mysql.cj.jdbc.Driver
    url:jdbc:mysql://rm-bp1xxpd6zdwc4dx5i.mysql.rds.aliyuncs.com:3306/basic_support_db?useSSL=true
    username:xnyl
    password:HT7FbUKn*DDO
  hikari:
    pool-name:DateHihaiCP
    minimnm-idle:5
    idle-timeout:10000000
    maximum-idle-size:20
    auto-commit:true
    max-lifetime:1000000
    connection-timeout:30000
    connection-test-query:select 1
mybatis-plus:
  mapper-locations:classpath*:mapper/*Mapper.xml
  type-aliaes-package:com.example.server.pojo
configuration:
  map-underscore-to-camel-case:false

logging:
  level:
    com.atlsh.springcloud.service.PaymentService: debug
