server:
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://47.101.191.102:3306/sys?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zeng&123aA
    hikari:
      pool-name: DateHihaiCP
      idle-timeout: 10000000
      auto-commit: true
      max-lifetime: 1000000
      connection-timeout: 30000
      connection-test-query: select 1
      minimum-idle: 5
      maximum-pool-size: 20
  main:
    allow-circular-references: true
  redis:
    #超时时间
    timeout: 100000ms
    #服务器地址
    host: localhost
    port: 6379
    database: 0
    password: HT7FbUKn*DDO
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最大连接租晒等待时间
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        min-idle: 5


mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.example.server.pojo
  configuration:
    map-underscore-to-camel-case: false


logging:
  level:
    com.example.server.mapper: debug

jwt:
  tokenHeader: Authorization
  secret: yeb-secret
  expiration: 604800
  tokenHead: Bearer

testng:
  port: 8082
  host: http://47.101.191.102


hbos:
  host: http://hbos-test.cfuture.shop/
  hostst: hbos-test.cfuture.shop
  user: hszy
  password: 123456